spring:
  application:
    name: code-craft-user
  session:
    store-type: redis
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${CODE_CRAFT_MYSQL_HOST:localhost}:${CODE_CRAFT_MYSQL_PORT:3307}/${CODE_CRAFT_MYSQL_DATABASE:ai_code_gen}?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
    username: ${CODE_CRAFT_MYSQL_USERNAME:ai_code_gen_user}
    password: ${CODE_CRAFT_MYSQL_PASSWORD:}
  data:
    redis:
      host: ${CODE_CRAFT_REDIS_HOST:localhost}
      port: ${CODE_CRAFT_REDIS_PORT:6379}
      database: 0
      password: ${CODE_CRAFT_REDIS_PASSWORD:}

server:
  port: 8124
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ws.codecraftuser.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

dubbo:
  registry:
    address: nacos://${CODE_CRAFT_NACOS_HOST:localhost}:${CODE_CRAFT_NACOS_PORT:8848}?username=${CODE_CRAFT_NACOS_USERNAME:nacos}&password=${CODE_CRAFT_NACOS_PASSWORD:}
    register-mode: instance
  protocol:
    name: tri
    port: 50051
    host: ${CODE_CRAFT_DUBBO_HOST:localhost}
  consumer:
    timeout: 60000
  provider:
    timeout: 60000
    executor: virtual-thread

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
