spring:
  application:
    name: yu-ai-code-screenshot
  profiles:
    active: local
server:
  port: 8127
  servlet:
    context-path: /api
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: ${COS_HOST:}
    secretId: ${COS_SECRET_ID:}
    secretKey: ${COS_SECRET_KEY:}
    region: ${COS_REGION:}
    bucket: ${COS_BUCKET:}
# Dubbo
dubbo:
  application:
    # 👇 必须加上这几行来解决冲突
    qos-enable: true
    qos-port: 33333  # 随便改个不一样的，比如 33333
    qos-accept-foreign-ip: false
  registry:
    address: nacos://localhost:8848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 50052
    host: localhost
  consumer:
    timeout: 120000
  provider:
    timeout: 120000